# Generated by Django 4.0.1 on 2022-02-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0002_autor_facebook_autor_instagram_autor_twitter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='email',
            field=models.EmailField(max_length=250, verbose_name='Email de Autor'),
        ),
    ]
