# Generated by Django 4.0.1 on 2022-02-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0004_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.URLField(max_length=255, verbose_name='URL de Imagen'),
        ),
    ]
